# Generated by Django 4.0.7 on 2023-11-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='organs.organ')),
            ],
        ),
    ]
