# Generated by Django 4.0.7 on 2023-11-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oxygen_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='departments.department')),
            ],
        ),
    ]
